/* ==========================================================================
   $LGL Miner — REFERRAL RISK ENGINE
   --------------------------------------------------------------------------
   Self-referral and referral-fraud detection.

   ┌───────────────────────────────────────────────────────────────────────┐
   │  NO FINGERPRINTING OF ANY KIND.                                       │
   │                                                                       │
   │  This module must never implement browser fingerprinting, device      │
   │  fingerprinting, canvas fingerprinting, WebGL/audio fingerprinting,   │
   │  font enumeration, screen-resolution hashing or any similar           │
   │  passive-identification technique.                                    │
   │                                                                       │
   │  The only device identifier used is the Device ID the application     │
   │  itself assigns and recognises on first run. Nothing is read from the │
   │  browser to try to identify the underlying hardware.                  │
   └───────────────────────────────────────────────────────────────────────┘

   Signals used, and nothing else:

     IP address            → reduced to a network token before it is stored
     Device ID             → the app-assigned ID, reduced to a device token
     Email                 → domain + local-part similarity, never the address
     Nigerian phone number → country + a shared-number comparison
     Referral relationship → who referred whom, and when
     Account history       → age, prior flags, prior reviews
     Network classification→ VPN / proxy / Tor / hosting / datacenter
     Activity patterns     → timing, volume, velocity

   PRIVACY RULES ENFORCED HERE
     · Raw IPs and raw Device IDs never leave this module's callers.
       `netToken()` / `devToken()` return truncated, non-reversible tokens.
     · No caller ever receives another user's IP or Device ID.
     · Only the minimum needed for fraud prevention is retained.

   A SINGLE SHARED IP IS NOT FRAUD. Legitimate users share home networks,
   offices, campuses and mobile carriers. The IP signal is deliberately
   weighted so that it can never, on its own, flag a referral. See
   IP_ONLY_MAX_CONTRIBUTION and the accompanying self-test.
   ========================================================================== */

/* ==========================================================================
   Referral lifecycle
   ========================================================================== */
export const REFERRAL_STATUS = {
  PENDING: 'pending_review',
  VERIFIED: 'verified',
  REJECTED: 'rejected',
};

export const REWARD_STATE = {
  ON_HOLD: 'on_hold',
  CREDITED: 'credited',
  VOID: 'void',
};

/** Where a referral goes once the risk engine has scored it. */
export const REVIEW_OUTCOME = {
  AUTO_VERIFY: 'auto_verify',   // low risk — still requires the server to credit
  MANUAL_REVIEW: 'manual_review',
  HIGH_RISK: 'high_risk',
};

/* ==========================================================================
   Privacy-preserving tokens
   --------------------------------------------------------------------------
   The prototype uses FNV-1a so the behaviour is inspectable offline.
   PRODUCTION MUST USE HMAC-SHA256 WITH A SERVER-SIDE SECRET PEPPER, and the
   token must never be computed in the browser — otherwise a client could
   enumerate the token space and recover the IP.
   ========================================================================== */

/** FNV-1a, 32-bit. Prototype only — see the note above. */
function fnv1a(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i += 1) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

const toToken = (prefix, value) => {
  if (!value) return null;
  const a = fnv1a(`${prefix}:${value}`).toString(36).padStart(7, '0');
  const b = fnv1a(`${prefix}:${value}:salt`).toString(36).padStart(7, '0');
  return `${a}${b}`.slice(0, 10).toUpperCase();
};

/**
 * Non-reversible network token for an IP address.
 * Two accounts on the same address produce the same token, which is all the
 * admin view needs — the address itself is never stored or displayed.
 */
export const netToken = (ip) => toToken('net', ip);

/**
 * Non-reversible token for the APPLICATION-ASSIGNED Device ID.
 * This is not a fingerprint: the ID is generated by the app, stored by the
 * app, and carries no information about the underlying hardware.
 */
export const devToken = (deviceId) => toToken('dev', deviceId);

/** Phone: keep the country and a comparison token, never the number. */
export const phoneToken = (msisdn) => toToken('tel', msisdn);

/** Email: keep the domain and a comparison token, never the address. */
export const emailToken = (email) => toToken('eml', String(email || '').toLowerCase().trim());

export function emailParts(email) {
  const raw = String(email || '').toLowerCase().trim();
  const at = raw.lastIndexOf('@');
  if (at < 1) return { domain: null, local: null, token: null };
  return {
    domain: raw.slice(at + 1),
    local: raw.slice(0, at),
    token: emailToken(raw),
  };
}

/** Normalises a Nigerian number to +234XXXXXXXXXX, or returns null. */
export function normaliseNgPhone(input) {
  const digits = String(input || '').replace(/[^\d+]/g, '');
  if (!digits) return null;
  let d = digits.replace(/^\+/, '');
  if (d.startsWith('234')) d = d.slice(3);
  else if (d.startsWith('0')) d = d.slice(1);
  if (d.length !== 10) return null;
  // Nigerian mobile prefixes (070/080/081/090/091 → 70/80/81/90/91)
  if (!/^[789]0/.test(d)) return null;
  return `+234${d}`;
}

/** Dice coefficient over character bigrams — a cheap local-part similarity. */
export function similarity(a, b) {
  const s1 = String(a || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  const s2 = String(b || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  if (!s1 || !s2) return 0;
  if (s1 === s2) return 1;
  if (s1.length < 2 || s2.length < 2) return 0;
  const grams = (s) => {
    const out = new Map();
    for (let i = 0; i < s.length - 1; i += 1) {
      const g = s.slice(i, i + 2);
      out.set(g, (out.get(g) || 0) + 1);
    }
    return out;
  };
  const g1 = grams(s1);
  const g2 = grams(s2);
  let hits = 0;
  for (const [g, n] of g1) if (g2.has(g)) hits += Math.min(n, g2.get(g));
  return (2 * hits) / ((s1.length - 1) + (s2.length - 1));
}

/* ==========================================================================
   Signal catalogue
   --------------------------------------------------------------------------
   Every signal carries an explicit weight and a plain-language rationale so
   the scoring is auditable. Weights are deliberately conservative: a signal
   only matters when it is corroborated.
   ========================================================================== */

export const REFERRAL_SIGNALS = [
  {
    id: 'same_device',
    weight: 45,
    label: 'Same Device ID as referrer',
    detail: 'Both accounts were created on the same app-assigned Device ID.',
    strength: 'strong',
  },
  {
    id: 'same_phone',
    weight: 40,
    label: 'Same phone number as referrer',
    detail: 'Both accounts share one Nigerian phone number.',
    strength: 'strong',
  },
  {
    id: 'tor',
    weight: 35,
    label: 'Tor exit node',
    detail: 'Traffic originated from a known Tor exit node.',
    strength: 'strong',
  },
  {
    id: 'hosting',
    weight: 25,
    label: 'Hosting / datacenter IP',
    detail: 'The network is a datacenter range, not a consumer connection.',
    strength: 'strong',
  },
  {
    id: 'email_similar',
    weight: 20,
    label: 'Email very similar to referrer',
    detail: 'Local parts match closely, e.g. name and name+1.',
    strength: 'medium',
  },
  {
    id: 'proxy',
    weight: 15,
    label: 'Proxy detected',
    detail: 'The connection appears to be proxied.',
    strength: 'medium',
  },
  {
    id: 'young_account',
    weight: 15,
    label: 'Account younger than the minimum age',
    detail: 'Created inside the referral minimum-age window.',
    strength: 'medium',
  },
  {
    id: 'device_overlap',
    weight: 15,
    label: 'Device shared with several accounts',
    detail: 'Three or more accounts report the same Device ID.',
    strength: 'medium',
  },
  {
    id: 'vpn',
    weight: 12,
    label: 'VPN detected',
    detail: 'A VPN is in use. Common among legitimate users — weak on its own.',
    strength: 'weak',
  },
  {
    id: 'instant_signup',
    weight: 12,
    label: 'Signed up immediately after the invite',
    detail: 'Created within minutes of the referrer generating a link.',
    strength: 'weak',
  },
  {
    id: 'email_domain_match',
    weight: 8,
    label: 'Same email domain as referrer',
    detail: 'Shared domain, which on free providers is weak evidence.',
    strength: 'weak',
  },
  {
    id: 'ip_overlap',
    weight: 6,
    label: 'Network shared with other accounts',
    detail: 'Three or more accounts share this network. Weighted low on purpose.',
    strength: 'weak',
  },
  {
    id: 'phone_missing',
    weight: 5,
    label: 'No phone number on file',
    detail: 'A verification channel is absent.',
    strength: 'weak',
  },
];

export const SIGNAL_BY_ID = Object.fromEntries(REFERRAL_SIGNALS.map((s) => [s.id, s]));

/**
 * The most the IP signal can ever contribute, no matter how many accounts
 * share the address. This is the guarantee that a shared network alone can
 * never flag a referral.
 */
export const IP_ONLY_MAX_CONTRIBUTION = 6;

/** Decision thresholds. */
export const RISK_THRESHOLDS = {
  /** Below this the referral may be auto-verified (the server still credits). */
  AUTO_VERIFY: 35,
  /** At or above this the referral is held for the Super Admin. */
  HIGH_RISK: 70,
};

/* ==========================================================================
   Evaluation
   ========================================================================== */

/**
 * Scores a referral from its signals.
 *
 * @param {object} input
 * @param {string|null} input.referrerDeviceToken  app-assigned Device ID token
 * @param {string|null} input.refereeDeviceToken
 * @param {string|null} input.referrerPhoneToken
 * @param {string|null} input.refereePhoneToken
 * @param {string}      input.referrerEmailLocal
 * @param {string}      input.refereeEmailLocal
 * @param {string|null} input.referrerEmailDomain
 * @param {string|null} input.refereeEmailDomain
 * @param {boolean}     input.vpn
 * @param {boolean}     input.proxy
 * @param {boolean}     input.tor
 * @param {boolean}     input.hosting
 * @param {number}      input.refereeAccountAgeHours
 * @param {number}      input.minAccountAgeHours
 * @param {number}      input.ipOverlapCount     accounts sharing this network
 * @param {number}      input.deviceOverlapCount accounts sharing this Device ID
 * @param {number|null} input.signupDelayMinutes
 * @returns {{score:number, level:string, outcome:string, indicators:Array, reason:string}}
 */
export function evaluateReferral(input) {
  const {
    referrerDeviceToken = null,
    refereeDeviceToken = null,
    referrerPhoneToken = null,
    refereePhoneToken = null,
    referrerEmailLocal = '',
    refereeEmailLocal = '',
    referrerEmailDomain = null,
    refereeEmailDomain = null,
    vpn = false,
    proxy = false,
    tor = false,
    hosting = false,
    refereeAccountAgeHours = 0,
    minAccountAgeHours = 24,
    ipOverlapCount = 1,
    deviceOverlapCount = 1,
    signupDelayMinutes = null,
  } = input;

  const hits = [];
  const add = (id, evidence) => hits.push({ id, ...SIGNAL_BY_ID[id], evidence });

  if (referrerDeviceToken && refereeDeviceToken && referrerDeviceToken === refereeDeviceToken) {
    add('same_device', 'Identical Device ID on both accounts.');
  }
  if (referrerPhoneToken && refereePhoneToken && referrerPhoneToken === refereePhoneToken) {
    add('same_phone', 'Identical phone number on both accounts.');
  }
  if (tor) add('tor', 'Matched a known Tor exit node.');
  if (hosting) add('hosting', 'Matched a hosting/datacenter range.');
  if (proxy) add('proxy', 'Proxy behaviour detected on the connection.');
  if (vpn) add('vpn', 'VPN detected. Weak on its own.');

  if (referrerEmailLocal && refereeEmailLocal) {
    const sim = similarity(referrerEmailLocal, refereeEmailLocal);
    if (sim >= 0.85) add('email_similar', `Local parts ${(sim * 100).toFixed(0)}% similar.`);
    else if (referrerEmailDomain && referrerEmailDomain === refereeEmailDomain) {
      add('email_domain_match', `Both use @${refereeEmailDomain}.`);
    }
  }

  if (refereeAccountAgeHours < minAccountAgeHours) {
    add('young_account', `Account is ${refereeAccountAgeHours}h old; the minimum is ${minAccountAgeHours}h.`);
  }
  if (!refereePhoneToken) add('phone_missing', 'No phone number recorded.');

  // IP overlap is capped so a shared network can never dominate the score.
  if (ipOverlapCount >= 3) {
    add('ip_overlap', `${ipOverlapCount} accounts share this network.`);
  }
  if (deviceOverlapCount >= 3) {
    add('device_overlap', `${deviceOverlapCount} accounts share this Device ID.`);
  }
  if (signupDelayMinutes != null && signupDelayMinutes >= 0 && signupDelayMinutes <= 10) {
    add('instant_signup', `Signed up ${signupDelayMinutes} min after the invite was generated.`);
  }

  // Sum, but hold the network signal to its ceiling.
  let score = 0;
  let ipContribution = 0;
  for (const h of hits) {
    if (h.id === 'ip_overlap') {
      const capped = Math.min(h.weight, IP_ONLY_MAX_CONTRIBUTION - ipContribution);
      ipContribution += capped;
      score += capped;
    } else {
      score += h.weight;
    }
  }
  score = Math.min(100, score);

  let outcome = REVIEW_OUTCOME.AUTO_VERIFY;
  if (score >= RISK_THRESHOLDS.HIGH_RISK) outcome = REVIEW_OUTCOME.HIGH_RISK;
  else if (score >= RISK_THRESHOLDS.AUTO_VERIFY) outcome = REVIEW_OUTCOME.MANUAL_REVIEW;

  const level = score >= RISK_THRESHOLDS.HIGH_RISK ? 'high'
    : score >= RISK_THRESHOLDS.AUTO_VERIFY ? 'medium' : 'low';

  return {
    score,
    /**
     * How much of the score came from the network signal. Exposed so the
     * "a shared IP is never fraud on its own" guarantee can be asserted
     * directly instead of being inferred from a total that other signals
     * also contribute to.
     */
    ipContribution,
    level,
    outcome,
    indicators: hits.sort((a, b) => b.weight - a.weight),
    reason: hits.length
      ? hits.map((h) => h.label).join('; ')
      : 'No risk indicators detected.',
  };
}

/* ==========================================================================
   Self-test cases
   --------------------------------------------------------------------------
   Exported so the test suite can assert the engine's guarantees directly,
   including the promise that a shared IP alone is never treated as fraud.
   ========================================================================== */
export const SELF_TEST_CASES = [
  {
    // Isolated on purpose: a verified phone and an old account so that the
    // network signal is the ONLY thing under test. Without the phone token
    // the unrelated `phone_missing` signal (+5) would confound the result.
    name: 'shared home network only',
    input: { ipOverlapCount: 4, refereeAccountAgeHours: 200, refereePhoneToken: 'PH' },
    expectMaxScore: IP_ONLY_MAX_CONTRIBUTION,
    expectIpContributionMax: IP_ONLY_MAX_CONTRIBUTION,
    expectOutcome: REVIEW_OUTCOME.AUTO_VERIFY,
  },
  {
    name: 'same Device ID',
    input: { referrerDeviceToken: 'AAA', refereeDeviceToken: 'AAA', ipOverlapCount: 1 },
    expectMinScore: 45,
    expectOutcome: REVIEW_OUTCOME.MANUAL_REVIEW,
  },
  {
    name: 'same device and same phone',
    input: {
      referrerDeviceToken: 'AAA', refereeDeviceToken: 'AAA',
      referrerPhoneToken: 'BBB', refereePhoneToken: 'BBB',
      referrerEmailLocal: 'chidi', refereeEmailLocal: 'chidi1',
      ipOverlapCount: 3, deviceOverlapCount: 3, refereeAccountAgeHours: 2,
    },
    expectMinScore: 85,
    expectOutcome: REVIEW_OUTCOME.HIGH_RISK,
  },
  {
    name: 'Tor exit node',
    input: { tor: true, ipOverlapCount: 1 },
    expectMinScore: 35,
    expectOutcome: REVIEW_OUTCOME.MANUAL_REVIEW,
  },
  {
    name: 'clean referral',
    input: {
      referrerDeviceToken: 'AAA', refereeDeviceToken: 'ZZZ',
      referrerPhoneToken: 'BBB', refereePhoneToken: 'YYY',
      referrerEmailLocal: 'chidi', refereeEmailLocal: 'amaka',
      referrerEmailDomain: 'gmail.com', refereeEmailDomain: 'yahoo.com',
      refereeAccountAgeHours: 900, ipOverlapCount: 1, deviceOverlapCount: 1,
    },
    expectMaxScore: 0,
    expectOutcome: REVIEW_OUTCOME.AUTO_VERIFY,
  },
];

/* ==========================================================================
   Network classification
   --------------------------------------------------------------------------
   VPN / proxy / Tor / hosting status is derived SERVER-SIDE from the
   connection, never from anything the browser reports about itself.
   ========================================================================== */
export function classifyNetwork({ asnType = null, torExit = false, vpnProvider = false, proxyHeaders = false } = {}) {
  return {
    tor: Boolean(torExit),
    vpn: Boolean(vpnProvider),
    proxy: Boolean(proxyHeaders),
    hosting: asnType === 'hosting' || asnType === 'datacenter',
  };
}
